### ISSUE TITLE
Encontrado solução de erro ao realizar testes unitários

### ISSUE THREAD

**Issue by farribeiro** [portabilis/i-educar#316]
> Olá e obrigado por nos ajudar a tornar o i-Educar um projeto mais estável. Para reportar seu bug use o template abaixo:
>
> **MENU:** Nesta seção deve ser apontado qual o menu no sistema deve ser realizada a alteração.
>
> **DESCRIÇÃO:** Nesta seção deve ser colocado uma descrição do problema ou necessidade.

Eu e o @JDias, percebemos que os testes falhavam pois não encontra o arquivo ini no projeto. Link https://github.com/portabilis/i-educar/issues/235#issuecomment-399084096

> **OBSERVAÇÕES:** Observações em geral sobre o problema apontado.
>

## AMBIENTE

- Plataforma utilizada (p.ex. Docker, instalação direta): Scrutinizer
- Sistema operacional e versão (p.ex. Ubuntu 16.04, Windows 7): não identificado
- Navegador e versão (p.ex. Chrome 35.9.9.9): não identificado
- Outros detalhes importantes: Log scrutinizer

```
PHP Fatal error:  Uncaught Exception: Arquivo ini com problemas de sintaxe. Verifique a sintaxe arquivo '/home/scrutinizer/build/ieducar/configuration/ieducar.ini'. in /home/scrutinizer/build/ieducar/lib/CoreExt/Config/Ini.class.php:136
Stack trace:
#0 /home/scrutinizer/build/ieducar/lib/CoreExt/Config/Ini.class.php(79): CoreExt_Config_Ini->loadFile('/home/scrutiniz...')
#1 /home/scrutinizer/build/ieducar/includes/bootstrap.php(98): CoreExt_Config_Ini->__construct('/home/scrutiniz...', 'production')
#2 /home/scrutinizer/build/ieducar/intranet/include/clsBanco.inc.php(31): require_once('/home/scrutiniz...')
#3 /home/scrutinizer/build/ieducar/tests/bootstrap.php(63): require_once('/home/scrutiniz...')
#4 /home/scrutinizer/build/ieducar/vendor/phpunit/phpunit/src/Util/Fileloader.php(64): include_once('/home/scrutiniz...')
#5 /home/scrutinizer/build/ieducar/vendor/phpunit/phpunit/src/Util/Fileloader.php(48): PHPUnit\Util\Fileloader::load('/home/scrutiniz...')
#6 /home/scrutinizer/build/ieducar/vendor/phpunit/phpunit/src/TextUI/Com in /home/scrutinizer/build/ieducar/lib/CoreExt/Config/Ini.class.php on line 136

Fatal error: Uncaught Exception: Arquivo ini com problemas de sintaxe. Verifique a sintaxe arquivo '/home/scrutinizer/build/ieducar/configuration/ieducar.ini'. in /home/scrutinizer/build/ieducar/lib/CoreExt/Config/Ini.class.php:136
Stack trace:
#0 /home/scrutinizer/build/ieducar/lib/CoreExt/Config/Ini.class.php(79): CoreExt_Config_Ini->loadFile('/home/scrutiniz...')
#1 /home/scrutinizer/build/ieducar/includes/bootstrap.php(98): CoreExt_Config_Ini->__construct('/home/scrutiniz...', 'production')
#2 /home/scrutinizer/build/ieducar/intranet/include/clsBanco.inc.php(31): require_once('/home/scrutiniz...')
#3 /home/scrutinizer/build/ieducar/tests/bootstrap.php(63): require_once('/home/scrutiniz...')
#4 /home/scrutinizer/build/ieducar/vendor/phpunit/phpunit/src/Util/Fileloader.php(64): include_once('/home/scrutiniz...')
#5 /home/scrutinizer/build/ieducar/vendor/phpunit/phpunit/src/Util/Fileloader.php(48): PHPUnit\Util\Fileloader::load('/home/scrutiniz...')
#6 /home/scrutinizer/build/ieducar/vendor/phpunit/phpunit/src/TextUI/Com in /home/scrutinizer/build/ieducar/lib/CoreExt/Config/Ini.class.php on line 136
```

## Solução

Acrescentar este trecho no build do testes

```
build:
    project_setup:
        before:
         - cp ieducar/configuration/ieducar.ini.sample ieducar/configuration/ieducar.ini
``` 

Ao fazer before do vuild ( um `cp`) dos testes do scrutinizer a saída de log tem o seguinte erro:

```
PHP Notice:  Undefined index: HTTP_HOST in /home/scrutinizer/build/ieducar/includes/bootstrap.php on line 104

Notice: Undefined index: HTTP_HOST in /home/scrutinizer/build/ieducar/includes/bootstrap.php on line 104
PHP Warning:  require_once(PHPUnit/Framework.php): failed to open stream: No such file or directory in /home/scrutinizer/build/ieducar/tests/TestCollector.php on line 31

Warning: require_once(PHPUnit/Framework.php): failed to open stream: No such file or directory in /home/scrutinizer/build/ieducar/tests/TestCollector.php on line 31
PHP Fatal error:  require_once(): Failed opening required 'PHPUnit/Framework.php' (include_path='/home/scrutinizer/build/ieducar/intranet:/home/scrutinizer/build/ieducar/lib:/home/scrutinizer/build/ieducar/modules:/home/scrutinizer/build/ieducar/.:/home/scrutinizer/build/ieducar/tests/unit:/home/scrutinizer/build/ieducar/tests/functional:/home/scrutinizer/build/ieducar/tests:/home/scrutinizer/build/ieducar/.:/home/scrutinizer/build/ieducar/intranet:.:/home/scrutinizer/.phpenv/versions/7.0.20/pear:/home/scrutinizer/.phpenv/versions/7.0.20/share/pyrus/.pear/php') in /home/scrutinizer/build/ieducar/tests/TestCollector.php on line 31

Fatal error: require_once(): Failed opening required 'PHPUnit/Framework.php' (include_path='/home/scrutinizer/build/ieducar/intranet:/home/scrutinizer/build/ieducar/lib:/home/scrutinizer/build/ieducar/modules:/home/scrutinizer/build/ieducar/.:/home/scrutinizer/build/ieducar/tests/unit:/home/scrutinizer/build/ieducar/tests/functional:/home/scrutinizer/build/ieducar/tests:/home/scrutinizer/build/ieducar/.:/home/scrutinizer/build/ieducar/intranet:.:/home/scrutinizer/.phpenv/versions/7.0.20/pear:/home/scrutinizer/.phpenv/versions/7.0.20/share/pyrus/.pear/php') in /home/scrutinizer/build/ieducar/tests/TestCollector.php on line 31
```

**Comment by farribeiro** [comment]
Sabe o que se pode fazer... Um PR com um cp do `ieducar.ini.sample` com outro nome

**Comment by JDias** [comment]
Talvez definir o host ajude? (Para o problema no bootstrap)

https://scrutinizer-ci.com/docs/configuration/build

Mas não sei o que é o PHPUnit/Framework.php

**Comment by farribeiro** [comment]
Solucionado com o PR #280
