### ISSUE TITLE
Liberação e atualização dos relatórios

### ISSUE THREAD

**Issue by edersoares** [portabilis/i-educar#390]
Hoje, 21 de agosto de 2018, alguns representantes da @portabilis fizeram uma call com @carolinesalib, @geekcom, @vitormattos e Luis Felipe para conversar um pouco mais sobre a liberação de alguns relatórios privados da Portabilis para a comunidade. 

Durante a call surgiram alguns insights para a modernização e padronização do desenvolvimento de relatórios usando o JasperReports e alguns passos foram acordados:

- A @portabilis irá liberar alguns relatórios genéricos para que possíveis contribuidores possam melhorá-los.
- Debater sobre quais as melhores práticas para o desenvolvimento/manutenção dos relatórios.
- Entender a dificuldade e o trabalho a ser realizado para migrar os relatórios atuais para a nova versão do JasperReports.
- Adicionar uma lib atualizada ao projeto, com o intuito de permitir o upgrade dos relatórios.
  - [PHPJasper](https://github.com/PHPJasper/phpjasper) é uma possível solução para ser utilizado para os novos relatórios.
  - [JasperPHP](https://github.com/portabilis/jasperphp) que é mantida pela @portabilis para retro compatibilidade com os relatórios atuais.
- Modificar os relatórios para utilizar um payload (JSON ou XML) como data source removendo as queries inseridas nos arquivos `.jrxml` e movendo as regras de negócio do relatório para a aplicação PHP.
  - Isso permitirá um melhor versionamento, manutenção e reaproveitamento (código, regras, dados).

O trabalho irá começar e gostaríamos da opinião de todos.

Obrigado.

**Comment by MarceloCajueiro** [comment]
Ótimo trabalho!

Tenho uma dúvida relacionada ao payload. Hoje quem executa a query não é o i-educar, certo? Ele manda para o jasper que vai se conectar ao banco e fazer a query. O lado positivo disso é que se for um relatório lento de gerar, ele não ocupa uma conexão no FPM (ou outro servidor).

Se a gente colocar a query para rodar no i-educar (todas as justificativas para fazer isso são plausíveis), qual a chance da gente sofrer com timeouts, fila de conexão, etc. caso a query seja lenta?

**Comment by vitormattos** [comment]
A query sendo executada pelo Jasper ou pelo i-Educar consumirá o mesmo tempo de execução.

Vantagens de se implementar a query do lado do i-Educar

1. Os metadados para geração dos relatórios já serão enviados todos formatados e tratados para o Jasper eliminando completamente a necessidade de manipulação de dados utilizando código Java.
2. As querys poderão ser versionadas fora de um `jrxml`, dentro do próprio i-Educar, possibilitando inclusive a possibilidade de reuso de métodos que já gerem metadados para listagens de dados.

Em relação a gargalos, o ideal para relatórios pesados demais (relatórios que levem mais de 10 segundos para serem gerados) é:

1. que sejam executados de forma assíncrona utilizando algum sistema de queue e modificar a ux para que após um usuário clicar no link para emitir o relatório ele veja uma tela de "aguarde" e depois verá o link para baixar o relatório.
2. criação de uma réplica do banco para que os relatórios sejam gerados na réplica e não onerem o banco principal.

Implementando estes dois pontos acaba completamente o custo de processamento nas máquinas que rodam a aplicação.

Não sei como os reports estão sendo gerados, se a partir de `jrxml` ou de `.jasper`, mas é super viável e aconselhável que os arquivos .jasper não sejam versionados e que a aplicação gere os .jasper em tempo de execução armazenando eles em cache para que não sejam gerados novamente caso já existam. Os `.jasper` são binários.

De qualquer forma, liberando alguns relatórios posso montar um modelo bem simples de arquitetura de software que gere tudo em um único servidor, o que roda a aplicação, sem réplica e nada mais, só para vermos como fica e se a proposta de arquitetura será boa.

**Comment by munizeverton** [comment]
Uma coisa levantada pelo @eberfreitas:
Em muitos casos os relatórios ficam gigantes, o que nesse caso seria um JSON ou XML gigante.
Vocês sabem dizer se tem limite de tamanho pra esse payload?

Talvez seja interessante fazer testes com conteúdo grande

**Comment by edersoares** [comment]
@MarceloCajueiro, acredito que nos primórdios do i-Educar um pouco antes de utilizar JasperReports o cenário era este, as queries muito lentas e agregado ao tempo de renderização do PDF o servidor da aplicação PHP ficava sobrecarregado facilmente se houvesse muita concorrência.

Hoje é o i-Educar que executa as queries e a renderização dos relatórios em desenvolvimento. 

Em produção a Portabilis tem uma solução com JasperReports v4.6.0 através de um web service, porém, mesmo assim, é o i-Educar que invoca a renderização através de uma chama RPC, mas como a execução da renderização é em outro servidor, o servidor da aplicação PHP fica livre para executar outros processos.

Como o @vitormattos disse:

> A query sendo executada pelo Jasper ou pelo i-Educar consumirá o mesmo tempo de execução.

Basicamente é isso, porém se houver um servidor especializado apenas em renderizar reports, com toda certeza a performance será melhor tanto para o servidor de relatórios quanto para o servidor de aplicação.

A intenção é atualizar a lib PHP que faz a intermediação entre PHP e JasperReports para podermos fazer o uso de diferentes data sources (JSON por exemplo) e remover as queries dos relatórios.

O intuito desta atualização é facilitar a manutenção e o reaproveitamento de código.

Hoje qualquer lib PHP que formos utilizar irá sim exigir mais do servidor de aplicação, porém podemos construir soluções que irão permitir a "terceirização" da renderização dos reports.

Quanto a questão de onerar a aplicação PHP com as queries sendo executadas no i-Educar, é o preço a ser pago por esta nova arquitetura. 

**Porém é de extrema importância entender que o que onera realmente a geração de um relatório é a sua renderização e não a sua consulta.** Se a consulta está onerando a geração do relatório, então há algo errado.

### Como utilizar os relatórios já inclusos no i-Educar

@vitormattos ainda não consegui trabalhar nas alterações dos relatórios que a Portabilis irá liberar para a comunidade, porém fiz alguns testes e tem um relatório que pode ser utilizado, basta seguir um passo a passo.

Instalar o projeto conforme o https://github.com/portabilis/i-educar/blob/master/README.md e então efetuar alguns cadastros:

- [Bairro](http://localhost:8001/intranet/public_bairro_cad.php)  - `Endereçamento > Cadastros > Bairros`
- [Logradouro](http://localhost:8001/intranet/public_logradouro_cad.php) - `Endereçamento > Cadastros > Logradouros`
- [CEP](http://localhost:8001/intranet/urbano_cep_logradouro_cad.php) - `Endereçamento > Cadastros > CEP`
  - Logradouro e Bairro são obrigatórios.
- [Pessoa Jurídica](http://localhost:8001/intranet/empresas_cad.php) - `Pessoas > Cadastros > Pessoas Jurídicas`
  - CEP é obrigatório.
- [Curso](http://localhost:8001/intranet/educar_curso_cad.php) - `Escola > Cadastros > Cursos`
  - Nível de Ensino, Tipo de Ensino são cadastros obrigatórios mas há um atalho na página para um cadastro rápido.
- [Escola](http://localhost:8001/intranet/educar_escola_cad.php) - `Escola > Cadastros > Escolas`
  - Curso é obrigatório.
  - Rede de Ensino é um cadastro obrigatório mas há um atalho na página para um cadastro rápido.
- [Biblioteca](http://localhost:8001/intranet/educar_biblioteca_cad.php) - ` Biblioteca > Cadastros > Bibliotecas`
  - Escola é obrigatório.
- [Editoras](http://localhost:8001/intranet/educar_acervo_editora_cad.php) - ` Biblioteca > Cadastros > Tipos > Obras > Editoras`
  - Biblioteca é obrigatório.

Logo após, será possível emitir um relatório de editoras no link http://localhost:8001/module/Reports/BibliotecaEditora.

Os links dos relatórios que já existem não estão disponíveis na interface, vou verificar o motivo e em seguida quero criar um PR para adicioná-los.

A ideia de gerar relatórios assincronamente é boa, porém vai requer maior arquitetura para rodar o i-Educar, mas é algo a ser pensado também.

O que o @munizeverton e @eberfreitas mencionaram a respeito do payload ser grande demais é algo a ser estudado e fica como ponto de atenção, mas eu acredito não ser um problema.

**Comment by giustin** [comment]
Legal eih galera! Parabéns aos envolvidos!

Lembrando que conforme anunciei na [live de lançamento da versão 2.0](https://youtu.be/1C3473KxIeM?t=3514), definimos o prazo máximo de 30/09 para disponibilizar um pacote com os melhores relatórios que já são utilizados por nossos clientes. Eles serão uma excelente base para termos como referência e expandirmos.

Vamos em frente!

**Comment by farribeiro** [comment]
Só uma questão não tão técnica mas valiosa Documentação

**Comment by vitormattos** [comment]
@edersoares a url http://localhost:8001/module/Reports/BibliotecaEditora retorna:
```
CoreExt_Exception_FileNotFoundException: Nenhuma classe CoreExt_Controller_Page_Interface para o controller informado no caminho: "/var/www/ieducar/modules/Reports/Views/BibliotecaEditoraController.php" in /var/www/ieducar/lib/CoreExt/Controller/Dispatcher/Strategy/PageStrategy.php:123
Stack trace:
#0 /var/www/ieducar/lib/CoreExt/Controller/Front.php(149): CoreExt_Controller_Dispatcher_Strategy_PageStrategy->dispatch()
#1 /var/www/ieducar/module/index.php(69): CoreExt_Controller_Front->dispatch()
#2 {main}
```

**Comment by edersoares** [comment]
@vitormattos você chegou a clonar o projeto de relatórios?

Segue link da instalação: https://github.com/portabilis/i-educar#instalando-relat%C3%B3rios
